language: node_js

git:
  depth: 1

node_js:
  - "12.22.7"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coveralls
